    
    eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
         defaultzone: http://ec2-50-18-148-105.us-west-1.compute.amazonaws.com:8761/eureka
            
    instance:
    hostname: localhost
  application:
    name: Department-Service
