    
    eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    service-url:
         defaultzone: http://localhost:8761/eureka
            
    instance:
    hostname: localhost
  application:
    name: Department-Service
